version: '3'
services:
  db:
    container_name: db_postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: golang
      POSTGRES_DB: books
    volumes:
      - ./seeds/api_books.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 5
      interval: 30s
  server:
    container_name: api_goLang
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db_postgres
      DB_PORT: 5432
      DB_USER: golang
      DB_PASSWORD: password
      DB_NAME: books
      PORT: 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/books" ]
      timeout: 10s
      retries: 5
      interval: 30s
    restart: always
