version: '3'
services:
  db:
    container_name: db_postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: golang
      POSTGRES_DB: books_api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 5
      interval: 30s
